/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatLogs: typeof import('./src/components/chat/ChatLogs.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconAlarmClock: typeof import('@element-plus/icons-vue')['AlarmClock']
    ElIconCalendar: typeof import('@element-plus/icons-vue')['Calendar']
    ElIconChatDotRound: typeof import('@element-plus/icons-vue')['ChatDotRound']
    ElIconCircleCheck: typeof import('@element-plus/icons-vue')['CircleCheck']
    ElIconCollection: typeof import('@element-plus/icons-vue')['Collection']
    ElIconCpu: typeof import('@element-plus/icons-vue')['Cpu']
    ElIconDelete: typeof import('@element-plus/icons-vue')['Delete']
    ElIconDocument: typeof import('@element-plus/icons-vue')['Document']
    ElIconDownload: typeof import('@element-plus/icons-vue')['Download']
    ElIconFolderAdd: typeof import('@element-plus/icons-vue')['FolderAdd']
    ElIconMenu: typeof import('@element-plus/icons-vue')['Menu']
    ElIconMessage: typeof import('@element-plus/icons-vue')['Message']
    ElIconOdometer: typeof import('@element-plus/icons-vue')['Odometer']
    ElIconPicture: typeof import('@element-plus/icons-vue')['Picture']
    ElIconRefreshRight: typeof import('@element-plus/icons-vue')['RefreshRight']
    ElIconRemove: typeof import('@element-plus/icons-vue')['Remove']
    ElIconSearch: typeof import('@element-plus/icons-vue')['Search']
    ElIconSetting: typeof import('@element-plus/icons-vue')['Setting']
    ElIconUpload: typeof import('@element-plus/icons-vue')['Upload']
    ElIconUploadFilled: typeof import('@element-plus/icons-vue')['UploadFilled']
    ElIconUser: typeof import('@element-plus/icons-vue')['User']
    ElIconUserFilled: typeof import('@element-plus/icons-vue')['UserFilled']
    ElIconView: typeof import('@element-plus/icons-vue')['View']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmojiManager: typeof import('./src/components/emoji/EmojiManager.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
